const gameData = [
    {
        id: 1,
        title: "Cyberpunk 2077",
        price: 599.99,
        originalPrice: 1199.99,
        discount: 50,
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
        heroImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop",
        rating: 4,
        reviews: 15420,
        genres: ["Acción", "RPG"],
        featured: true,
        isNew: true,
        description: "Una aventura de mundo abierto ambientada en Night City, una megalópolis obsesionada con el poder, el glamour y las modificaciones corporales.",
        developer: "CD Projekt Red",
        publisher: "CD Projekt",
        releaseDate: "10 Dic 2020"
    },
    {
        id: 2,
        title: "The Witcher 3: Wild Hunt",
        price: 399.99,
        originalPrice: 799.99,
        discount: 50,
        image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=300&fit=crop",
        heroImage: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=400&fit=crop",
        rating: 5,
        reviews: 28500,
        genres: ["RPG", "Aventura"],
        featured: true,
        description: "Eres Geralt de Rivia, cazador de monstruos mercenario. Ante ti se extiende un continente devastado por la guerra e infestado de monstruos.",
        developer: "CD Projekt Red",
        publisher: "CD Projekt",
        releaseDate: "18 May 2015"
    },
    {
        id: 3,
        title: "Grand Theft Auto V",
        price: 299.99,
        originalPrice: 599.99,
        discount: 50,
        image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 45200,
        genres: ["Acción", "Aventura"],
        featured: true,
        description: "Cuando un joven estafador callejero, un ladrón de bancos retirado y un psicópata aterrador se ven envueltos con los criminales más peligrosos.",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        releaseDate: "14 Abr 2015"
    },
    {
        id: 4,
        title: "Call of Duty: Modern Warfare III",
        price: 1199.99,
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 23400,
        genres: ["Acción", "Shooter"],
        isNew: true,
        description: "Call of Duty: Modern Warfare III lleva a los jugadores a un conflicto global inmersivo que presenta el regreso de los Operadores icónicos.",
        developer: "Infinity Ward",
        publisher: "Activision",
        releaseDate: "10 Nov 2023"
    },
    {
        id: 5,
        title: "FIFA 24",
        price: 1199.99,
        image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 12400,
        genres: ["Deportes", "Simulación"],
        description: "EA SPORTS FC 24 te da la bienvenida al Juego del Mundo: la experiencia de fútbol más auténtica que jamás hayas vivido.",
        developer: "EA Sports",
        publisher: "Electronic Arts",
        releaseDate: "29 Sep 2023"
    },
    {
        id: 6,
        title: "Elden Ring",
        price: 999.99,
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        rating: 5,
        reviews: 18700,
        genres: ["Acción", "RPG"],
        description: "Álzate, Tiznado, y que la gracia te guíe para blandir el poder del Anillo de Elden y convertirte en un Señor de Elden en las Tierras Intermedias.",
        developer: "FromSoftware",
        publisher: "Bandai Namco",
        releaseDate: "25 Feb 2022"
    },
    {
        id: 7,
        title: "Age of Empires IV",
        price: 799.99,
        originalPrice: 999.99,
        discount: 20,
        image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 8900,
        genres: ["Estrategia", "Simulación"],
        description: "Una de las franquicias de estrategia en tiempo real más queridas regresa para desafiar a los jugadores de nuevas maneras.",
        developer: "Relic Entertainment",
        publisher: "Xbox Game Studios",
        releaseDate: "28 Oct 2021"
    },
    {
        id: 8,
        title: "Cities: Skylines II",
        price: 899.99,
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 5600,
        genres: ["Simulación", "Estrategia"],
        isNew: true,
        description: "Construye la ciudad de tus sueños y transforma cualquier entorno con el poder creativo que solo Cities: Skylines puede ofrecer.",
        developer: "Colossal Order",
        publisher: "Paradox Interactive",
        releaseDate: "24 Oct 2023"
    },
    {
        id: 9,
        title: "Red Dead Redemption 2",
        price: 799.99,
        originalPrice: 1199.99,
        discount: 33,
        image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop",
        rating: 5,
        reviews: 34200,
        genres: ["Aventura", "Acción"],
        description: "América, 1899. El fin de la era del Salvaje Oeste ha comenzado. Después de que un atraco sale mal en el pueblo occidental de Blackwater.",
        developer: "Rockstar Games",
        publisher: "Rockstar Games",
        releaseDate: "5 Dic 2019"
    },
    {
        id: 10,
        title: "NBA 2K24",
        price: 1099.99,
        image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 9800,
        genres: ["Deportes", "Simulación"],
        description: "NBA 2K24 es un simulador de baloncesto que te permite vivir la experiencia completa de la NBA.",
        developer: "Visual Concepts",
        publisher: "2K Sports",
        releaseDate: "8 Sep 2023"
    },
    {
        id: 11,
        title: "Minecraft",
        price: 449.99,
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        rating: 5,
        reviews: 89300,
        genres: ["Aventura", "Simulación"],
        description: "Minecraft es un juego sobre colocar bloques y vivir aventuras. ¡Explora mundos generados aleatoriamente y construye cosas increíbles!",
        developer: "Mojang Studios",
        publisher: "Microsoft",
        releaseDate: "18 Nov 2011"
    },
    {
        id: 12,
        title: "Fortnite",
        price: 0,
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 156200,
        genres: ["Battle Royale", "Acción"],
        description: "Fortnite es el Battle Royale gratuito completamente multiplataforma donde puedes construir, explorar y luchar para ser el último en pie.",
        developer: "Epic Games",
        publisher: "Epic Games",
        releaseDate: "21 Jul 2017"
    },
    {
        id: 13,
        title: "Valorant",
        price: 0,
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 78900,
        genres: ["Shooter", "Estrategia"],
        description: "VALORANT es un shooter táctico 5v5 basado en personajes donde la puntería precisa se combina con habilidades únicas de agente.",
        developer: "Riot Games",
        publisher: "Riot Games",
        releaseDate: "2 Jun 2020"
    },
    {
        id: 14,
        title: "Among Us",
        price: 89.99,
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 234500,
        genres: ["Multijugador", "Estrategia"],
        description: "¡Juega en línea o por WiFi local con 4-15 jugadores mientras intentas preparar tu nave espacial para la partida!",
        developer: "InnerSloth",
        publisher: "InnerSloth",
        releaseDate: "15 Jun 2018"
    },
    {
        id: 15,
        title: "The Sims 4",
        price: 199.99,
        originalPrice: 399.99,
        discount: 50,
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
        rating: 4,
        reviews: 45600,
        genres: ["Simulación", "Aventura"],
        description: "Crea Sims únicos y controla sus vidas. Personaliza todo, desde sus personalidades hasta sus hogares.",
        developer: "Maxis",
        publisher: "Electronic Arts",
        releaseDate: "2 Sep 2014"
    }
];
